%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/rrockne/Library/CloudStorage/OneDrive-SharedLibraries-CityofHopeNationalMedicalCenter/PSON AML State-Transition - CML model/CML_state-space/cml_sampleInfo_dataTable.csv
%
% Auto-generated by MATLAB on 05-Apr-2023 12:17:22

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 62, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["sample", "PC1", "PC2", "assay", "mouse_id", "tissue", "timepoint", "project", "batch", "treatment", "genotype", "sex", "sample_date", "dob", "dod", "sample_weeks", "age_at_end", "age_at_start", "age_at_sample", "samtoolsflagstat_total", "samtoolsmapped_passed", "biotype_countspercent_rRNA", "dupradardupRadar_intercept", "picardPERCENT_DUPLICATION", "qualimap5_3_bias", "qualimapreads_aligned", "rseqcproper_pairs_percent", "salmonpercent_mapped", "salmonnum_mapped", "samtoolserror_rate", "samtoolsnon_primary_alignments", "samtoolsreads_mapped", "samtoolsreads_properly_paired_percent", "samtoolsreads_MQ0_percent", "samtoolsraw_total_sequences", "staruniquely_mapped_percent", "staruniquely_mapped", "fastqc_rawpercent_duplicates", "fastqc_rawpercent_gc", "fastqc_rawpercent_fails", "fastqc_rawtotal_sequences", "fastqc_trimmedpercent_duplicates", "fastqc_trimmedpercent_gc", "fastqc_trimmedavg_sequence_length", "fastqc_trimmedpercent_fails", "fastqc_trimmedtotal_sequences", "myeloid", "CML_space", "myeloid_class", "state_class", "time_class", "Group", "HSA_ABL1_gene", "HSA_BCR_ABL1_gene", "HSA_BCR_gene", "HSA_MYH11_gene", "state_chr", "myeloid_chr", "oldstate_class", "rx_class", "state_rx", "group_name"];
opts.VariableTypes = ["double", "double", "double", "categorical", "double", "categorical", "double", "double", "double", "categorical", "categorical", "categorical", "datetime", "datetime", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical", "categorical", "double", "double", "double", "double", "double", "categorical", "double", "categorical", "double", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["assay", "tissue", "treatment", "genotype", "sex", "dod", "myeloid", "myeloid_class", "time_class", "Group", "myeloid_chr", "rx_class", "group_name"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "sample_date", "InputFormat", "MM/dd/yy");
opts = setvaropts(opts, "dob", "InputFormat", "MM/dd/yy");
opts = setvaropts(opts, ["sample", "project", "batch", "state_chr", "state_rx"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["sample", "project", "batch", "state_chr", "state_rx"], "ThousandsSeparator", ",");

% Import the data
cmldata = readtable("/Users/rrockne/Library/CloudStorage/OneDrive-SharedLibraries-CityofHopeNationalMedicalCenter/PSON AML State-Transition - CML model/CML_state-space/cml_sampleInfo_dataTable.csv", opts);


%% Clear temporary variables
clear opts